#!/usr/bin/env python3
"""
Run CMS Combine to extract limits for all regions.

This script runs Combine on all datacards generated by process_regions.py.
"""

import argparse
import subprocess
import sys
from pathlib import Path
import re


def run_combine(datacard_file, region_name, combine_method="AsymptoticLimits", verbose=True):
    """
    Run Combine on a datacard file.

    Parameters:
    -----------
    datacard_file : Path
        Path to datacard.txt file
    region_name : str
        Region name for output naming
    combine_method : str
        Combine method (AsymptoticLimits, HybridNew, etc.)
    verbose : bool
        Print output

    Returns:
    --------
    limits : dict
        Dictionary with limit values
    """
    datacard_file = Path(datacard_file)
    if not datacard_file.exists():
        print(f"✗ Datacard not found: {datacard_file}")
        return None

    # Change to datacard directory
    work_dir = datacard_file.parent
    datacard_name = datacard_file.name

    # Run combine
    cmd = [
        "combine",
        "-M", combine_method,
        str(datacard_name),
        "-n", region_name
    ]

    if verbose:
        print(f"\n  Running: {' '.join(cmd)}")
        print(f"  Directory: {work_dir}")

    try:
        result = subprocess.run(
            cmd,
            cwd=str(work_dir),
            capture_output=True,
            text=True,
            check=True
        )

        if verbose:
            print(result.stdout)
            if result.stderr:
                print("STDERR:", result.stderr)

        # Parse limits from output
        limits = parse_combine_output(result.stdout)
        return limits

    except subprocess.CalledProcessError as e:
        print(f"✗ Combine failed: {e}")
        if verbose:
            print(f"STDOUT: {e.stdout}")
            print(f"STDERR: {e.stderr}")
        return None
    except FileNotFoundError:
        print("✗ 'combine' command not found. Is CMS Combine installed?")
        print("  Install from: https://cms-analysis.github.io/HiggsAnalysis-CombinedLimit/")
        return None


def parse_combine_output(output):
    """
    Parse Combine output to extract limit values.

    Parameters:
    -----------
    output : str
        Combine stdout

    Returns:
    --------
    limits : dict
        Dictionary with limit values
    """
    limits = {}

    # Pattern for expected limits
    # Expected 50.0%: r < 2.34
    pattern = r"Expected\s+([\d.]+)%:\s+r\s+[<>]\s+([\d.]+)"
    matches = re.findall(pattern, output)

    for percentile, value in matches:
        limits[f"expected_{percentile}"] = float(value)

    # Observed limit (if present)
    obs_pattern = r"Observed Limit:\s+r\s+[<>]\s+([\d.]+)"
    obs_match = re.search(obs_pattern, output)
    if obs_match:
        limits["observed"] = float(obs_match.group(1))

    return limits


def find_all_datacards(output_dir):
    """
    Find all datacard.txt files in output directory.

    Parameters:
    -----------
    output_dir : Path
        Output directory from process_regions.py

    Returns:
    --------
    datacards : list
        List of (datacard_path, region_name) tuples
    """
    output_dir = Path(output_dir)
    plots_dir = output_dir / "plots"

    if not plots_dir.exists():
        print(f"✗ Plots directory not found: {plots_dir}")
        return []

    datacards = []
    for region_dir in plots_dir.iterdir():
        if region_dir.is_dir():
            datacard_file = region_dir / "datacard.txt"
            if datacard_file.exists():
                region_name = region_dir.name
                datacards.append((datacard_file, region_name))

    return datacards


def main():
    parser = argparse.ArgumentParser(
        description="Run Combine on all datacards from process_regions.py"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="output",
        help="Output directory from process_regions.py"
    )
    parser.add_argument(
        "--method",
        type=str,
        default="AsymptoticLimits",
        choices=["AsymptoticLimits", "HybridNew", "Frequentist"],
        help="Combine method to use"
    )
    parser.add_argument(
        "--region",
        type=str,
        default=None,
        help="Run on specific region only (e.g., 'sr1b')"
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress Combine output"
    )

    args = parser.parse_args()

    output_dir = Path(args.output_dir)

    # Find all datacards
    print("="*70)
    print("Finding Datacards")
    print("="*70)
    datacards = find_all_datacards(output_dir)

    if not datacards:
        print("✗ No datacards found!")
        sys.exit(1)

    print(f"  Found {len(datacards)} datacards:")
    for _, region_name in datacards:
        print(f"    - {region_name}")

    # Filter by region if specified
    if args.region:
        datacards = [(dc, rn) for dc, rn in datacards if rn == args.region]
        if not datacards:
            print(f"✗ Region '{args.region}' not found!")
            sys.exit(1)

    # Run Combine on each datacard
    print("\n" + "="*70)
    print(f"Running Combine ({args.method})")
    print("="*70)

    all_limits = {}
    for datacard_file, region_name in datacards:
        print(f"\n  Region: {region_name}")
        limits = run_combine(
            datacard_file,
            region_name,
            combine_method=args.method,
            verbose=not args.quiet
        )

        if limits:
            all_limits[region_name] = limits
            print(f"    ✓ Limits extracted:")
            if "expected_50.0" in limits:
                print(f"      Expected 50%: r < {limits['expected_50.0']:.4f}")
            if "observed" in limits:
                print(f"      Observed: r < {limits['observed']:.4f}")
        else:
            print(f"    ✗ Failed to extract limits")

    # Summary
    print("\n" + "="*70)
    print("Summary")
    print("="*70)

    if all_limits:
        print("\nExpected 50% limits (r < value):")
        for region_name, limits in sorted(all_limits.items()):
            if "expected_50.0" in limits:
                print(f"  {region_name:20s}: {limits['expected_50.0']:8.4f}")
    else:
        print("✗ No limits extracted!")
        sys.exit(1)

    print("\n" + "="*70)
    print("✓ Complete!")
    print("="*70)
    print(f"\nCombine output files are in: {output_dir}/plots/*/")


if __name__ == "__main__":
    main()
